import type { Metadata } from "next";
import {  Noto_Naskh_Arabic, Noto_Sans, Archivo, Fraunces } from "next/font/google";
import "./globals.css";


const notoNaskhArabic = Noto_Naskh_Arabic({
  variable: "--font-noto-naskh-arabic",
  subsets: ["arabic"],
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "WikiCommons Wallpaper API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} ${fraunces.variable} ${notoNaskhArabic.variable} ${notoSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
